INSERT INTO `proyecto_final`.`usuarios` (`password`, `username`) VALUES ('$2a$10$P9i2Hb9pKLPyxhhl33gzFOUaVtoxe7EDez91Dq/rcC8bsKqVKb/Xe', 'admin');
INSERT INTO `proyecto_final`.`usuarios` (`password`, `username`) VALUES ('$2a$10$P9i2Hb9pKLPyxhhl33gzFOUaVtoxe7EDez91Dq/rcC8bsKqVKb/Xe', 'user');
INSERT INTO `proyecto_final`.`roles` (`nombre`) VALUES ('ROLE_ADMIN');
INSERT INTO `proyecto_final`.`roles` (`nombre`) VALUES ('ROLE_USER');
INSERT INTO `proyecto_final`.`usuariorol` (`idrol`, `idusuario`) VALUES ('1', '1');
INSERT INTO `proyecto_final`.`usuariorol` (`idrol`, `idusuario`) VALUES ('2', '2');
INSERT INTO `proyecto_final`.`fincas` (`idfinca`, `denominacion`,`direccion`,`referenciacatastral`,`superficie`,`localizacion`) VALUES ('1', 'Mieres','C/ Mieres 20','AAA000',300,'12°22,13.32″N, 23°19,20.18″E');
INSERT INTO `proyecto_final`.`fincas` (`idfinca`, `denominacion`,`direccion`,`referenciacatastral`,`superficie`,`localizacion`) VALUES ('2', 'Aviles Norte','C/ Aguilera 56','BBB000',500,'16°45,67.34″N, 11°12,67.10″E');
INSERT INTO `proyecto_final`.`fincas` (`idfinca`, `denominacion`,`direccion`,`referenciacatastral`,`superficie`,`localizacion`) VALUES ('3', 'Montañera Friu','Avda/Correo','CCC000',100,'43°15,11.3"N, 2°55,20.5"E');
INSERT INTO `proyecto_final`.`fincas` (`idfinca`, `denominacion`,`direccion`,`referenciacatastral`,`superficie`,`localizacion`) VALUES ('4', 'Rio Sur','C/RioEo','DDD000',600,'37°47,42.6"N, 122°26,32.4"W');
INSERT INTO `proyecto_final`.`fincas` (`idfinca`, `denominacion`,`direccion`,`referenciacatastral`,`superficie`,`localizacion`) VALUES ('5', 'Cordillera Exterior','C/Montaña','EEE000',200,'37.794833, -122.442333');
INSERT INTO `proyecto_final`.`variedades` (`idvariedad`, `nombre`) VALUES ('1', 'Raxao');
INSERT INTO `proyecto_final`.`variedades` (`idvariedad`, `nombre`) VALUES ('2', 'Regona');
INSERT INTO `proyecto_final`.`variedades` (`idvariedad`, `nombre`) VALUES ('3', 'Perico');
INSERT INTO `proyecto_final`.`variedades` (`idvariedad`, `nombre`) VALUES ('4', 'Verdialona');
INSERT INTO `proyecto_final`.`variedades` (`idvariedad`, `nombre`) VALUES ('5', 'De la Riega');
INSERT INTO `proyecto_final`.`variedades` (`idvariedad`, `nombre`) VALUES ('6', 'Blanquina');
INSERT INTO `proyecto_final`.`variedades` (`idvariedad`, `nombre`) VALUES ('7', 'Carrio');
INSERT INTO `proyecto_final`.`variedades` (`idvariedad`, `nombre`) VALUES ('8', 'Collaos');
INSERT INTO `proyecto_final`.`variedades` (`idvariedad`, `nombre`) VALUES ('9', 'Raxao Roxa');
INSERT INTO `proyecto_final`.`variedades` (`idvariedad`, `nombre`) VALUES ('10', 'Xuanina');
INSERT INTO `proyecto_final`.`arboles` (`idarbol`, `fila`,`columna`,`ubicacion`,`idfinca`,`idvariedad`,`estado`) VALUES ('1','1', '1','35.6895° N, 139.6917°','1','1','SANO');
INSERT INTO `proyecto_final`.`arboles` (`idarbol`, `fila`,`columna`,`ubicacion`,`idfinca`,`idvariedad`,`estado`) VALUES ('2', '1', '2', '35.6895° N, 139.6917°', '1', '2', 'SANO');
INSERT INTO proyecto_final.arboles (idarbol, fila, columna, ubicacion, idfinca, idvariedad, estado) VALUES ('3', '1', '3', '51.5074° N, 0.1278° W', '1', '10', 'MUERTO');
INSERT INTO proyecto_final.arboles (idarbol, fila, columna, ubicacion, idfinca, idvariedad, estado)VALUES ('4', '2', '1', '37.7749° N, 122.4194° W', '1', '6', 'SANO');
INSERT INTO proyecto_final.arboles (idarbol, fila, columna, ubicacion, idfinca, idvariedad, estado)VALUES ('5', '2', '2', '48.8566° N, 2.3522° E', '1', '1', 'ENFERMO');
INSERT INTO proyecto_final.arboles (idarbol, fila, columna, ubicacion, idfinca, idvariedad, estado)VALUES ('6', '2', '3', '51.5072° N, 0.1277° W', '1', '3', 'SANO');
INSERT INTO proyecto_final.arboles (idarbol, fila, columna, ubicacion, idfinca, idvariedad, estado)VALUES ('7', '3', '1', '35.6895° N, 139.6917° E', '1', '9', 'MUERTO');
INSERT INTO proyecto_final.arboles (idarbol, fila, columna, ubicacion, idfinca, idvariedad, estado)VALUES ('8', '3', '2', '37.7749° N, 122.4194° E', '1', '4', 'SANO');
INSERT INTO proyecto_final.arboles (idarbol, fila, columna, ubicacion, idfinca, idvariedad, estado)VALUES ('9', '3', '3', '51.5074° N, 0.1278° E', '1','5','SANO');


